import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { generateMainLinks, MainLink } from './scripts/generate-links';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const mainLinks = generateMainLinks();

const _sidebars = mainLinks.reduce((acc, link: MainLink) => {
  return {
    ...acc,
    [link.id]: [
      {
        type: 'autogenerated',
        dirName: link.to,
      },
    ],
  };
}, {});

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  docsSidebar: [
    {
      type: 'autogenerated', dirName: '.'
    }
  ],
  */

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  ..._sidebars
};

export default sidebars;
