import clsx from 'clsx';
import Heading from '@theme/Heading';
import styles from './styles.module.css';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

interface FeatureItem {
  label: string;
  metadata: any;
};

function Feature({ label, metadata }: FeatureItem) {
  return (
    <div className={clsx('col col--3', styles.feature)}>
      <Link to={`docs/${metadata?.to}`} className={clsx('unstyled-link')}>
        <div>
          <Heading as="h2">{label}</Heading>
          <p>{metadata?.description}</p>
        </div>
      </Link>
    </div>
  );
}

export default function HomepageFeatures(): JSX.Element {
  const { siteConfig } = useDocusaurusContext();
  const { themeConfig } = siteConfig;

  const FeatureList: FeatureItem[] = (themeConfig.navbar as any).items
    .filter((item: any) => item?.metadata?.autogenerated);

  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
